<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SVINDK00069" ignored="0" name="Base Class" tests="8" failures="4" timestamp="2019-10-04T13:25:55 IST" time="143.775" errors="0">
  <testcase name="function1" time="45.463" classname="qa.reportValidation.testScript.web.BaseClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at qa.reportValidation.testScript.web.BaseClass.function1(BaseClass.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- function1 -->
  <testcase name="function2" time="16.471" classname="qa.reportValidation.testScript.web.BaseClass"/>
  <testcase name="function3" time="17.348" classname="qa.reportValidation.testScript.web.BaseClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at qa.reportValidation.testScript.web.BaseClass.function3(BaseClass.java:54)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- function3 -->
  <testcase name="function4" time="12.958" classname="qa.reportValidation.testScript.web.BaseClass"/>
  <testcase name="function5" time="9.868" classname="qa.reportValidation.testScript.web.BaseClass"/>
  <testcase name="function6" time="8.897" classname="qa.reportValidation.testScript.web.BaseClass"/>
  <testcase name="function7" time="8.703" classname="qa.reportValidation.testScript.web.BaseClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at qa.reportValidation.testScript.web.BaseClass.function7(BaseClass.java:107)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- function7 -->
  <testcase name="function8" time="11.038" classname="qa.reportValidation.testScript.web.BaseClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at qa.reportValidation.testScript.web.BaseClass.function8(BaseClass.java:120)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- function8 -->
</testsuite> <!-- Base Class -->
